#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings

yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config window_border                off
yabai -m config window_border_width          3

yabai -m config active_window_border_color   0xffffffff
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings

yabai -m config layout                       bsp
yabai -m config top_padding                  7
yabai -m config bottom_padding               7
yabai -m config left_padding                 7
yabai -m config right_padding                7
yabai -m config window_gap                   7

# Disable `bsp` layout on space {5, 6}
# yabai -m config --space 5 layout float
# yabai -m config --space 6 layout float

# Unmanaged applications
yabai -m rule --add app=".* Preferences" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="Activity Monitor" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="1Password .*" manage=off
yabai -m rule --add app="Spotify" manage=off
yabai -m rule --add app="Slack" manage=off
yabai -m rule --add app="Discord" manage=off
yabai -m rule --add app="Telegram" manage=off
yabai -m rule --add app="DBngin" manage=off
yabai -m rule --add app="Notes" manage=off
yabai -m rule --add title="Preferences" manage=off

# limelight
killall limelight &> /dev/null
limelight --config /Users/emredeger/.limelightrc &> /dev/null &

echo "yabai configuration loaded.."
